backend:
  name: local-backend
  branch: master

local_backend: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# Location where files will be stored in the repo.
media_folder: "src/assets/images"

# The src attribute for uploaded media.
public_folder: "src/assets/images"

collections:
- name: "general"
  label: "Általános beállítások"
